#!/usr/bin/env bash
# Define a function that takes a string as an argument and returns the third word in the string, which is the record type
function get_record_type {
    local record_type=$(echo "$1" | awk '{print $4}')
    echo "$record_type"
}
function get_destination {
    local destination=$(echo "$1" | awk '{print $5}')
    echo "$destination"
}
domain="$1"
subdomain="$2"
if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi
for subdomain in "${subdomains[@]}"; do
    record="$(dig "$subdomain.$domain" | grep -A1 "ANSWER SECTION:" |awk 'NR==2')"
    record_type=$(get_record_type "$record")
    destination=$(get_destination "$record")
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
done
